//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomStringGeneratorLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomStringGeneratorLib.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A charset must be specified in order to create a random string..
        /// </summary>
        internal static string CHARSET_NOT_SPECIFIED {
            get {
                return ResourceManager.GetString("CHARSET_NOT_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected charset is too small to generate a random string from..
        /// </summary>
        internal static string CHARSET_TOO_SMALL {
            get {
                return ResourceManager.GetString("CHARSET_TOO_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;fromInclusive&apos; cannot be greater than toExclusive..
        /// </summary>
        internal static string FROM_INCLUSIVE_VALUE_MUST_BE_LESS_THAN_TO_EXCLUSIVE_VALUE {
            get {
                return ResourceManager.GetString("FROM_INCLUSIVE_VALUE_MUST_BE_LESS_THAN_TO_EXCLUSIVE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The individual length parameter values (such as minUpperCaseLetters) must be greater than or equal to zero..
        /// </summary>
        internal static string LENGTH_MUST_BE_GREATER_OR_EQUAL_TO_ZERO {
            get {
                return ResourceManager.GetString("LENGTH_MUST_BE_GREATER_OR_EQUAL_TO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the random string must be a positive non-zero integer..
        /// </summary>
        internal static string LENGTH_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("LENGTH_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To prevent memory issues the maximum length for random strings is {0}..
        /// </summary>
        internal static string MAX_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("MAX_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one charset is needed to generate a random string..
        /// </summary>
        internal static string NONE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("NONE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;toExclusive&apos; must be greater than or equal to zero..
        /// </summary>
        internal static string TO_EXCLUSIVE_VALUE_MUST_BE_GREATER_OR_EQUAL_TO_ZERO {
            get {
                return ResourceManager.GetString("TO_EXCLUSIVE_VALUE_MUST_BE_GREATER_OR_EQUAL_TO_ZERO", resourceCulture);
            }
        }
    }
}
